=== meganveldhuis/ClimaFi/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ClimaFy Settings",
  "type": "object",
  "properties": {
    "controller": { "type": "integer" },
    "controllerTypes": { "type": "object" },
    "thermostatTypes": { "type": "object" },
    "components": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "settingType": { "type": "string" },
          "data": {
            "type": "array",
            "properties": {
              "zoneName": { "type": "string" },
              "thermostatID": { "type": "integer" },
              "setPoint": { "type": "float" },
              "isCool": { "type": "boolean" },
              "name": { "type": "string" },
              "type": { "type": "integer" }
            }
          }
        }
      }
    }
  }
}

=== meganveldhuis/ClimaFi/OVERALLsettings.json
{
  "controller": 0,
  "controllerTypes": {
    "ZoneValveController": 0,
    "ZonePumpController": 1,
    "FanCoilController": 2
  },
  "thermostatTypes": {
    "CLASSIC": 0,
    "THREE_WIRE": 1,
    "NETWORKED": 2
  },
  "components": [
    {
      "settingType": "controlledZoneOutputs",
      "data": [
        {
          "zoneName": "livingRoomZoneName",
          "thermostatID": 1,
          "setPoint": 23,
          "isCool": true
        },
        {
          "zoneName": "bedroomZoneName",
          "thermostatID": 2,
          "setPoint": 23,
          "isCool": false
        },
        {
          "zoneName": "basementZoneName",
          "thermostatID": 7,
          "setPoint": 23,
          "isCool": true
        },
        {
          "zoneName": "topFloorZoneName",
          "thermostatID": 4,
          "setPoint": 23,
          "isCool": true
        }
      ]
    },
    {
      "settingType": "Thermostat",
      "data": [
        {
          "name": "topFloorThermostat",
          "type": 1
        },
        {
          "name": "thermostatName",
          "type": 2
        },
        {
          "name": "thermostatName",
          "type": 0
        },
        {
          "name": "thermostatName",
          "type": 1
        }
      ]
    },
    {
      "settingType": "thermistorPort",
      "data": [
        {
          "name": "thermistorName"
        },
        {
          "name": "secondThermistorName"
        }
      ]
    },
    {
      "settingType": "ADCOutput",
      "data": [
        {
          "name": "fanCoilName",
          "thermostatID": 1,
          "setPoint": 24
        }
      ]
    }
  ]
}
